name: Daily Can I Email... Repo Check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository caniemail
        uses: actions/checkout@v2
        with:
          repository: "hteumeuleu/caniemail"
          path: "caniemail"

      - name: Check for updates
        run: |
          cd caniemail
          git fetch origin
          CHANGES=$(git diff --name-only origin/main --since="24 hours ago")
          if [ -z "$CHANGES" ]; then
            echo "No changes detected in the last 24 hours"
            exit 0
          else
            echo "Changes detected in the last 24 hours in the following files:"
            echo "$CHANGES"
          cd ..

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
